apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: madhurasatihelloworldmadhur 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: madhurasatihelloworldmadhur 
    spec:
      containers:
        - name: madhurasatihelloworldmadhur 
          image: madhurtest.azurecr.io/madhurasatihelloworldmadhur
          ports:
          - containerPort: 8080